### ISSUE TITLE
Please create a PR with the suggested fixes against vscode

### ISSUE THREAD

**Issue by egamma** [mrmlnc/vscode-emmet-fix#1]
A PR against vscode with the suggested fixes would be much appreciated. We will get them into the June update.

**Comment by mrmlnc** [comment]
Thanks you for feedback, Erich. I'll try to do it.

**Comment by egamma** [comment]
:rose:. 

Please, also try the new emmet commands `wrap with abbreviation`, `update tag`, and `remove tag` that is now in the [insiders](https://code.visualstudio.com/insiders) build.

**Comment by mrmlnc** [comment]
@egamma I looked through the source code of Emmet and found a simple way to correct support the Sass and Stylus.

PR: https://github.com/Microsoft/vscode/pull/7887

I tried to unpublished an extension, using the command `vsce unpublish mrmlnc.vscode-emmet-fix -p tokenPAT`, but got the error:

```
Error: Failed Request: Bad Request(400) - You can't remove extension 'Emmet fix' because it's installed on at least one account.
```

Is it possible to fix it or need to publish the new version, explaining about the changes?

**Comment by egamma** [comment]
Thanks for the PR.

Regarding unpublishing. Did you try to just run `vsce unpublish` from the folder of the extension.

**Comment by mrmlnc** [comment]
@egamma, yes.

I git clone this repo and run `vsce unpublish`:

```
$ vsce unpublish
This will FOREVER delete 'mrmlnc.vscode-emmet-fix'! Are you sure? [y/N] y
Error: Failed Request: Bad Request(400) - You can't remove extension 'Emmet fix' because it's installed on at least one account.
```

It turns out I can't delete an extension if it has been set at least once.

**Comment by egamma** [comment]
@seanmcbreen any idea what the issue is?

**Comment by seanmcbreen** [comment]
I'm going to reach out to the marketplace team - this seams like a strange error.  Awesome work on all of your extensions BTW - thanks!
Sean

**Comment by mrmlnc** [comment]
@seanmcbreen, any news?)

**Comment by seanmcbreen** [comment]
Hi sorry for the delay here - we have a fix going into the marketplace to enable you to unpublished.  IT's still probably a week off for now.  I'll update the thread as soon as I've received a confirmation it's fixed.

**Comment by mrmlnc** [comment]
@seanmcbreen, Thank you for the information :+1:

**Comment by mrmlnc** [comment]
Well, I uninstalled the extension from the store.

**Comment by egamma** [comment]
great, thanks 🌹
